"""New"

Revision ID: 712648b3a243
Revises: 
Create Date: 2025-02-26 11:01:06.325925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '712648b3a243'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('user_role', sa.String(length=100), nullable=False),
    sa.Column('oil_production', sa.Float(), nullable=False),
    sa.Column('gas_production', sa.Float(), nullable=False),
    sa.Column('avg_well_debit', sa.Float(), nullable=False),
    sa.Column('equipment_failures', sa.Integer(), nullable=False),
    sa.Column('downtime_hours', sa.Float(), nullable=False),
    sa.Column('electricity_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('anomalies')
    op.drop_table('wells')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wells',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wells_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('flow_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_maintenance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wells_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('anomalies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anomaly_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('norm_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], name='anomalies_well_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='anomalies_pkey')
    )
    op.drop_table('users')
    op.drop_table('reports')
    # ### end Alembic commands ###
